### ISSUE TITLE
Unable to import resources into terraform state

### ISSUE THREAD

**Issue by kiraum** [catchpoint/terraform-provider-catchpoint#2]
Hi,

Using the current provider version, we are unable to import resources into terraform state:
```
% terraform import module.ping.ping_test.test123 test123
module.ping.ping_test.test123: Importing from ID "test123"...
module.ping.ping_test.test123: Import prepared!
  Prepared ping_test for import
module.ping.ping_test.test123: Refreshing state... [id=test123]
╷
│ Error: 400 bad request
│
│
╵
```

```
% terraform version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/catchpoint/catchpoint v0.2.1
```

Thanks, and please let me know if you need something else from my side.

**Comment by vikashkuma** [comment]
@kiraum 
Can you please try this 
terraform import ping_test.test123 123456

123456 is your test id which you want to import

**Comment by kiraum** [comment]
@vikashkuma I did tried that in the past, the provider crashs, also we miss the terraform import section in the provider documentation.

```

% terraform import module.ping.ping_test.test_tfg 2341414
module.ping.ping_test.test_tfg: Importing from ID "2341414"...
module.ping.ping_test.test_tfg: Import prepared!
  Prepared ping_test for import
module.ping.ping_test.test_tfg: Refreshing state... [id=2341414]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-catchpoint_v0.2.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x102bcb6b4]

goroutine 86 [running]:
catchpoint-provider/catchpoint.flattenTest(0x1400043c800)
        catchpoint-provider/catchpoint/flatten_all_test_type.go:279 +0x15e4
catchpoint-provider/catchpoint.resourcePingTestRead(0x1400068ab80, {0x102f64740?, 0x1400010f200})
        catchpoint-provider/catchpoint/resource_ping_test_type.go:506 +0x23c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x103094660?, {0x103094660?, 0x14000422300?}, 0xd?, {0x102f64740?, 0x1400010f200?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:712 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140003afb20, {0x103094660, 0x14000422300}, 0x1400013ab60, {0x102f64740, 0x1400010f200})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000378408, {0x1030945b8?, 0x14000433440?}, 0x140004334c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140002c4d20, {0x103094660?, 0x14000695a10?}, 0x1400040d0e0)
        github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:746 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x103060ce0?, 0x140002c4d20}, {0x103094660, 0x14000695a10}, 0x1400040d080, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140003188c0, {0x1030972e0, 0x14000003380}, 0x14000632480, 0x140003b9800, 0x1034fa4f0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x140003188c0, {0x1030972e0, 0x14000003380}, 0x14000632480, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x298

Error: The terraform-provider-catchpoint_v0.2.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```
